# Generated by Django 5.0.3 on 2024-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number_of_days', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
